### ISSUE TITLE
Root definition

### ISSUE THREAD

**Issue by hpatoio** [drm/MelpPagesBundle#1]
Hello, I was following your tutorial here http://melp.nl/2011/07/symfony2-phpcr-doctrine2-jackalope-recipe/ and I've pulled out your code.

I just have a question: in the constructor you define the "root" property like  $this->root = '/' . trim($root, '/') . '/'; but if the user define the $root parameter in the config as an empty string the value for root will be "//" and this create invalid paths for documents.

I've modified your code adding this line in the constructor $this->root = ($this->root == '//') ? '/' : $this->root; 

Do you agree ?

**Comment by drm** [comment]
This issue somehow escaped my attention, sorry for that. I am not planning on maintaining this :)
